config/routes.rb
Rails.application.routes.draw do

  match 'ajoke/clients' => 'clients#index', via: [:get]

  match 'ajoke/clients/create' => 'clients#create', via: [:post]

  match 'ajoke/clients/edit' => 'clients#edit', via: [:get]
  patch 'ajoke/clients/update' => 'clients#update'
  match 'ajoke/clients/update_client' => 'clients#update_client', via: [:post]
  match 'ajoke/clients/delete' => 'clients#delete', via: [:get]

  get 'images/upload_images'

  get 'ajoke/options'

  get 'ajoke/galleries'

  get 'ajoke/schedule'

  get 'ajoke/notifications'

  get 'ajoke/profile'

  match '/ajoke/create_gallery' => 'ajoke#create_gallery', via: [:post]
  match '/ajoke/upload_images' => 'ajoke#upload_images', via: [:get]
  match '/ajoke/add_photos' => 'ajoke#add_photos', via: [:get]
  match '/ajoke/uploaded_images' => 'ajoke#uploaded_images', via: [:get]
  match '/ajoke/update_cov' => 'ajoke#update_cov', via: [:post]
  match '/ajoke/save_images', :to => 'ajoke#save_images', :via => [:post, :put]
  match '/ajoke/upload_home' => 'ajoke#upload_home_images', via: [:get]
  match '/ajoke/delete_image' => 'ajoke#delete_image', via: [:post]

  devise_for :users

  devise_scope :user do
    match '/users/sign_out' => 'devise/sessions#destroy', via: [:get, :delete]
  end

  match '/about', :to => 'pages#about', :via => [:get]
  match '/gallery', :to => 'pages#gallery', :via => [:get]
  match '/galleries', :to => 'pages#galleries', :via => [:get]
  match '/view_gallery', :to => 'pages#view_gallery', :via => [:get]
  match '/packages', :to => 'pages#packages', :via => [:get]
  match '/contact', :to => 'pages#contact', :via => [:get, :post]
  match '/album_request', :to => 'pages#album_request', :via => [:get, :post]
  match '/ajoke', :to => 'ajoke#galleries', :via => [:get]
  match '/ajoke/save_cover', :to => 'ajoke#save_cover', :via => [:post, :put]

  root :to => 'pages#home'

end

app/controllers/ajoke_controller.rb
class AjokeController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_action :authenticate_user!
  before_action :admin_check

  def options
    @title = "Options"
    t = Gallery.arel_table
    @gallery = Gallery.where((t[:name].eq("Wedding")).or(t[:name].eq("Reception")).or(t[:name].eq("Outdoor")))
    # @pictures = @gallery.pictures.build
    @image = Image.where(:gallery_id => @gallery)
    @photo = @image.order(created_at: :desc)
    @photos = @photo.paginate(:page => params[:page],:per_page => 6)

  end

  def upload_home_images
    @title = "Upload photos"
    t = Gallery.arel_table
    @galleries = Gallery.where((t[:name].eq("Wedding")).or(t[:name].eq("Reception")).or(t[:name].eq("Outdoor")))

  end

  def save_cover
    @gallery = Gallery.find(1)
    @pic = Picture.where(gallery_id: @gallery).first
    p_attr = params[:picture]
    p_attr[:image] = params[:picture][:image].first if params[:picture][:image].class == Array

    unlocked_params = ActiveSupport::HashWithIndifferentAccess.new(p_attr)
    #@picture = @gallery.pictures.build(unlocked_params)

    @images = Picture.new(unlocked_params)

    if @images.save
      respond_to do |format|
        format.html {
          render :json => @images.to_jq_upload,
          :content_type => 'text/html',
          :layout => false
        }
        format.json {
          render :json => @images.to_jq_upload
        }
      end
    else
      render :json => [{:error => "custom_failure"}], :status => 304
    end


  end

  def create_gallery
    name = params[:name]
    date =  Date.strptime(params[:event_date], "%m/%d/%Y")
    #puts 'name=' + name +  '  date=' + date.to_s
    @gallery = Gallery.new(:name => name, :event_date => date)

    if @gallery.save
      redirect_to ajoke_upload_images_path(:gallery => @gallery)
    else
      render :galleries
    end
  end

  def upload_images
    @gallery = Gallery.find(params[:gallery])
    @clients = Client.all
    @client = ClientGallery.find_by(gallery_id: @gallery.id)
    @image = Image.where(:gallery_id => @gallery)
    @photo = @image.order(created_at: :desc)
    @photos = @photo.paginate(:page => params[:page],:per_page => 6)
    @title = "Upload images to " + @gallery.name
  end

  def add_photos
    @gallery = Gallery.find(params[:gallery])
    @title = "Upload images to " + @gallery.name
  end

  def uploaded_images
    @image = Image.where(:gallery_id => params[:gallery])
    @photo = @image.order(created_at: :desc)
    @photos = @photo.paginate(:page => params[:page],:per_page => 6)
    render :partial => "uploaded_images"
  end

  def update_cov
    img_id = params[:img]
    gal_id = params[:gal]
    gal = Gallery.find(gal_id)
    gal.cover = img_id
    if gal.save
      render :json => 'success'
    end
  end

  def delete_image
    image = Image.find(params["img"])
    image.delete
    render :json => {status => "ok"}
  end

  def save_images
    p_attr = params[:image]
    #puts '>>>atrs=' + p_attr.to_s
    p_attr[:image] = params[:image][:image].first if params[:image][:image].class == Array
    unlocked_params = ActiveSupport::HashWithIndifferentAccess.new(p_attr)

    @images = Image.new(unlocked_params)

    if @images.save
      respond_to do |format|
        format.html {
          render :json => @images.to_jq_upload,
          :content_type => 'text/html',
          :layout => false
        }
        format.json {
          render :json => @images.to_jq_upload
        }
      end
    else
      render :json => [{:error => "custom_failure"}], :status => 304
    end

  end

  def galleries
    t = Gallery.arel_table
    @gallery = Gallery.new
    @title = "Galleries"
    @gal = Gallery.where((t[:name].eq("Home")).or(t[:name].eq("Wedding")).or(t[:name].eq("Reception")).or(t[:name].eq("Outdoor")))
    @gals = @gal.order(created_at: :asc)
    @galleries = @gals.paginate(:page => params[:page],:per_page => 6)
  end

  def clients
    @title = "Clients"
  end

  def schedule
    @title = "Schedule"
  end

  def notifications
    @title = "Nitifications"
  end

  def profile
    @title = "Profile"
  end

end

app/helpers/ajoke_helper.rb
module AjokeHelper
end

app/views/ajoke/_uploaded_images.html.erb
<div  class="gallery masonry-gallery">
<% @photos.each do |photo| %>
  <figure class="gallery-item" style="position: absolute; left: 0px; top: 0px;">
    <header class='gallery-icon'>
      <a ><img class="galimg" src="<%= photo.image.disp %>" alt="" /></a>
    </header>
    <figcaption class='gallery-caption'>
      <div  class="entry-summary">
        <p class='cover_img' data-id='<%= photo.id %>' ><a href="#" >Delete image</a></p>
      </div>
    </figcaption>
  </figure>
<% end %>
<% if @photos.length == 0 %>
<p style="text-align:center;">No photos added yet <p>
<% end%>
</div>
<div style="text-align:center;padding:10px"> <%= will_paginate @photos %> </div>

app/views/ajoke/add_photos.html.erb
<h3 style="text-align:center;padding-bottom: 30px;"><%= @gallery.name %> </h3>
<%= form_for :image, url: ajoke_save_images_path , :html => { :multipart => true, :id => "fileupload"  } do |f| %>
<div class=" fileupload-buttonbar">


    <div class="column-grid column-grid-5">

      <div class="column column-span-2 column-push-0 column-first">
      <p>
        Add photos to the gallery
      </p>
      <!-- The global progress state -->
            <div id="progressbar" class="col-lg-5 fileupload-progress fade">
                <!-- The global progress bar -->
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                </div>
                <!-- The extended global progress state -->
                <div class="progress-extended">&nbsp;</div>
            </div>
      </div>
      <div class="column column-span-3 column-push-0 column-last">
        <input id="image_file" type="file" style="visibility: hidden;height: 0;width: 0;display: block;" multiple="multiple" name="image[image][]">
        <input class="button blue" type="button" value="Browse" id="browse" />
        <input class="button orange" type="button" value="View Gallery" onclick="location.href='<%= ajoke_upload_images_path %>?gallery=<%=params[:gallery] %>';" />
        <input type="hidden" value='<%=params[:gallery] %>' name="image[gallery_id]" />


      </div>

      <!-- The table listing the files available for upload/download -->
      <table role="presentation" style="width:80%" class="table table-striped"><tbody class="files"></tbody></table>
    </div>


  </div>

<% end %>


<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img  style="width:50px;" height=50 src="{%=file.thumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.deleteUrl) { %}
                <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" name="delete" value="1" class="toggle">
            {% } else { %}
                <button class="button green">
                    <i class="icon-checkmark2"></i>
                    <span>Done</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script src="/javascripts/vendor/jquery.ui.widget.js"></script>
<!-- The Templates plugin is included to render the upload/download listings -->
<script src="/javascripts/tmpl.min.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script src="/javascripts/load-image.all.min.js"></script>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="/javascripts/jquery.iframe-transport.js"></script>
<!-- The basic File Upload plugin -->
<script src="/javascripts/jquery.fileupload.js"></script>
<!-- The File Upload processing plugin -->
<script src="/javascripts/jquery.fileupload-process.js"></script>
<!-- The File Upload image preview & resize plugin -->
<script src="/javascripts/jquery.fileupload-image.js"></script>
<!-- The File Upload validation plugin -->
<script src="/javascripts/jquery.fileupload-validate.js"></script>
<!-- The File Upload user interface plugin -->
<script src="/javascripts/jquery.fileupload-ui.js"></script>

<script>
$(function () {



  //$("#uploaded_img").load('/ajoke/uploaded_images?gallery=<%=params[:gallery] %>');


  $("input:file").change(function (){
       $('#uploaded_img').hide();
       $("#progressbar").show();
     });
  $("#progressbar").hide();
    $('#browse').click(function() { $('#image_file').click();  });
    'use strict';
    // Initialize the jQuery File Upload widget:
    $('#fileupload').fileupload({
      acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
      //url : '<%= ajoke_save_cover_path %>'
      autoUpload: true
  /*  progressall: function (e, data) {
          var progress = parseInt(data.loaded / data.total * 100, 10);
          $('#progress .progress-bar').css(
              'width',
              progress + '%'
          );
    } */
  });
  // Load existing files:
    $('#fileupload').addClass('fileupload-processing');
    $.ajax({
            // Uncomment the following to send cross-domain cookies:
            //xhrFields: {withCredentials: true},
            url: $('#fileupload').fileupload('option', 'url'),
            dataType: 'json',
            context: $('#fileupload')[0]
        }).always(function () {
            $(this).removeClass('fileupload-processing');
        }).done(function (result) {
            $(this).fileupload('option', 'done')
                .call(this, $.Event('done'), {result: result});

        });
  $("#fileupload").bind("fileuploaddone", function (e, data) {
    toastr['success']("Cover image updated with " + data.result.files[0].name);
  //  $("#progressbar").hide();
  //  window.location.href = '<%=ajoke_upload_images_path %>?gallery=<%=params[:gallery] %>';

  });


});
</script>

app/views/ajoke/clients.html.erb
<h1>Ajoke#clients</h1>
<p>Find me in app/views/ajoke/clients.html.erb</p>

app/views/ajoke/galleries.html.erb
<div class="whistles whistles-toggle">
	<h3 style="float:right;" class="whistle-title">Create new gallery</h3>
	<div class="whistle-content" >
		<form action="/ajoke/create_gallery" method="post" id="commentform" class="comment-form" novalidate>
			<%= render 'layouts/error_messages', :object => @gallery %>
			<div style="width:30%;float:left;padding-right:20px;">
				<p class="comment-form-author">
					<label for="name">Gallery Name <span class="required">*</span></label>
					<input id="name" name="name" type="text" placeholder="e.g. Tanu weds Manu" size="20" required />
				</p>
			</div>
			<div style="width:30%;float:left;">
				<p class="comment-form-email">
					<label for="date">Date of event <span class="required">*</span></label>
					<input id="event_date" name="event_date" type="text" placeholder="Pick a date" size="30" required /></p>
				</div>
				<p class="form-submit" style="padding-top:35px;padding-left:20px;">
					<input name="submit" type="submit" id="submit" value="Create" />
				</p>
			</form>
		</div>
	</div>
	<!-- Gallery __-->
	<div style="text-align:center;padding:10px"> <%= will_paginate @galleries %> </div>
	<div  class="gallery masonry-gallery">
		<% @galleries.each do |gal| %>
		<% unless gal.cover.nil?
			pic = gal.images.find(gal.cover)
		else
			pic = gal.images.last
		end %>

		<figure class="gallery-item" style="position: absolute; left: 0px; top: 0px;">
			<header class='gallery-icon'>
				<a href="<%=ajoke_upload_images_path %>?gallery=<%=gal.id %>" ><img class="galimg" data-id='<%= gal.id %>' src="<%= ( pic.nil? )? '/images/photography/default.jpg' : pic.image.disp %>" alt="" /></a>
			</header>
			<figcaption class='gallery-caption'>
				<div  class="entry-summary">
					<h3><%= gal.name %></h3>
					<p id='img'><%= gal.event_date %></p>
				</div>
			</figcaption>
		</figure>
		<% end %>
		<% if @galleries.length == 0 %>
			<p style="text-align:center;">No Gallaries created yet. <p>
		<% end%>

		</div>
		<div style="text-align:center;padding:10px"> <%= will_paginate @galleries %> </div>

<!-- Javascripts ______________________________________-->
<script>
$(function() {
  $('#event_date').datepicker();
});
</script>

app/views/ajoke/notifications.html.erb
<h1>Ajoke#notifications</h1>
<p>Find me in app/views/ajoke/notifications.html.erb</p>

app/views/ajoke/options.html.erb
<!-- Heading ___-->
<%= form_for :picture, url: ajoke_save_cover_path , :html => { :id => "fileupload"  } do |f| %>
<div class=" fileupload-buttonbar">
    <div class="progressbar fileupload-progressbar nofade"><div style="width:0%;"></div></div>
    <div class="column-grid column-grid-5">
      <div class="column column-span-2 column-push-0 column-first">
      <p>
      <span>Change Home page cover</span><br/>
      <small>Aspect ratio : 1600 x 1100 px</small>
      </p>
      <!-- The global progress state -->
            <div id="progressbar" class="col-lg-5 fileupload-progress fade">
                <!-- The global progress bar -->
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                </div>
                <!-- The extended global progress state -->
                <div class="progress-extended">&nbsp;</div>
            </div>
      </div>
      <div class="column column-span-3 column-push-0 column-last">
        <input id="picture_image" type="file" multiple="multiple" style="visibility: hidden;height: 0;width: 0;display: block;" name="picture[image]">
        <input class="button blue" type="button" value="Browse" id="browse" />
        <input type="hidden" value='1' name="picture[gallery_id]" />

      </div>
      <!-- The table listing the files available for upload/download -->
      <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
    </div>


  </div>

<% end %>
<div id="uploaded_img">
<!-- Gallery __-->
    <%= render '/ajoke/uploaded_images' %>
</div>
<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img  style="width:50px;" height=50 src="{%=file.thumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.deleteUrl) { %}
                <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" name="delete" value="1" class="toggle">
            {% } else { %}
                <button class="button green">
                    <i class="icon-checkmark2"></i>
                    <span>Done</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script src="/javascripts/vendor/jquery.ui.widget.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script src="/javascripts/load-image.all.min.js"></script>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="/javascripts/jquery.iframe-transport.js"></script>
<!-- The basic File Upload plugin -->
<script src="/javascripts/jquery.fileupload.js"></script>
<!-- The File Upload processing plugin -->
<script src="/javascripts/jquery.fileupload-process.js"></script>
<!-- The File Upload image preview & resize plugin -->
<script src="/javascripts/jquery.fileupload-image.js"></script>
<!-- The File Upload validation plugin -->
<script src="/javascripts/jquery.fileupload-validate.js"></script>
<!-- The File Upload user interface plugin -->
<script src="/javascripts/jquery.fileupload-ui.js"></script>

<script>
$(function () {
    $("#progressbar").hide();
    $('#browse').click(function() { $('#picture_image').click(); $("#progressbar").show(); });


    'use strict';

    // Initialize the jQuery File Upload widget:
    $('#fileupload').fileupload({
      //url : '<%= ajoke_save_cover_path %>'
      autoUpload: true

  /*  progressall: function (e, data) {
          var progress = parseInt(data.loaded / data.total * 100, 10);
          $('#progress .progress-bar').css(
              'width',
              progress + '%'
          );
    } */


  });


  // Load existing files:
    $('#fileupload').addClass('fileupload-processing');
    $.ajax({
            // Uncomment the following to send cross-domain cookies:
            //xhrFields: {withCredentials: true},
            url: $('#fileupload').fileupload('option', 'url'),
            dataType: 'json',
            context: $('#fileupload')[0]
        }).always(function () {
            $(this).removeClass('fileupload-processing');
        }).done(function (result) {
            $(this).fileupload('option', 'done')
                .call(this, $.Event('done'), {result: result});
        });

  $("#fileupload").bind("fileuploaddone", function (e, data) {
    toastr['success']("Cover image updated with <img height='40' width='40' style='float:left;padding-right:5px' src='" + data.result.files[0].thumbnailUrl + "' />"+ data.result.files[0].name );
    $("#progressbar").hide();
  });
});

</script>

app/views/ajoke/profile.html.erb
<h1>Ajoke#profile</h1>
<p>Find me in app/views/ajoke/profile.html.erb</p>

app/views/ajoke/schedule.html.erb
<h1>Ajoke#schedule</h1>
<p>Find me in app/views/ajoke/schedule.html.erb</p>

app/views/ajoke/upload_images.html.erb
<h3 style="text-align:center;"><%= @gallery.name %> </h3>

<div class="whistles whistles-toggle">
  <h3 style="float:right;" class="whistle-title"><a href="<%= ajoke_add_photos_path %>?gallery=<%=params[:gallery] %>">Add photos</a></h3>
  <div class="whistle-content" >
  </div>

  <!-- <h3 style="float:left;" class="whistle-title">Add Client</h3> -->
  <!-- <div class="whistle-content" >
    <form action="/ajoke/clients/update_client" method="post" id="commentform" class="comment-form" novalidate>
      <%= render 'layouts/error_messages', :object => @gallery %>
        <div style="width:30%;float:left;padding-right:20px;">
          <p class="comment-form-author">

            <%= select_tag "client[name]", options_from_collection_for_select(@clients, "id", "name", (@client.nil?)? '' : @client.client_id), placeholder: "Select Client", class: "chosen-select", size:"30" %>
            <input type="hidden" name="client[id]" value="<%= (@client.nil?)? '' : @client.id %>" />
            <input type="hidden" name="client[gallery]" value="<%= params[:gallery] %>" />
          </p>
        </div>

        <p class="form-submit" style="padding-top:35px;padding-left:20px;">
          <input id="updt_cl" name="submit" type="submit" id="submit" value="Save" />
          <a href="<%=ajoke_clients_path %>"><input type="button" value="Add new" /></a>
        </p>

    </form>
  </div> -->

</div>


<div id="uploaded_img">
<!-- Gallery __-->
    <%= render '/ajoke/uploaded_images' %>
</div>
<!-- Chosen -->
<script src="/javascripts/chosen/chosen.jquery.js"></script>
<script>
$(function () {

  var config = {
                  '.chosen-select'           : {},
                  '.chosen-select-deselect'  : {allow_single_deselect:true},
                  '.chosen-select-no-single' : {disable_search_threshold:10},
                  '.chosen-select-no-results': {no_results_text:'Oops, nothing found!'},
                  '.chosen-select-width'     : {width:"95%"}
              }
              for (var selector in config) {
                  $(selector).chosen(config[selector]);

              }

  //$("#uploaded_img").load('/ajoke/uploaded_images?gallery=<%=params[:gallery] %>');

  $("#uploaded_img").on("click",".cover_img",function(event){
    //console.log("here?");
    item = $(this).parents(".gallery-item");
    $.ajax({
         type: "POST",
         dataType: 'json',
         url: '/ajoke/delete_image',
         data : "img="+ $(this).attr('data-id') + "&gal=" + <%= params[:gallery]%>,
         success: function(result) {
              item.remove();
              toastr['warning']("Image deleted from gallery!");
         },
         error: function(err){
           console.log("error = " + JSON.stringify(err));
           toastr['error']("Error deleting the image");
         }
     });

  });

  $($('#commentform')).submit(function(event) {
    // Stop the browser from submitting the form.
    event.preventDefault();

    var formData = $($('#commentform')).serialize();
    //console.log("here?");
    //toastr['success']("Cover image updated for the gallery");
    $.ajax({
         type: "POST",
         url: '/ajoke/clients/update_client',
         dataType: 'json',
         data : formData,

     }).done(function(response) {
       console.log(result);
      });
      toastr['success']("Client details updated!");
  });

});
</script>