config/routes.rb
Rails.application.routes.draw do

  match 'ajoke/clients' => 'clients#index', via: [:get]

  match 'ajoke/clients/create' => 'clients#create', via: [:post]

  match 'ajoke/clients/edit' => 'clients#edit', via: [:get]
  patch 'ajoke/clients/update' => 'clients#update'
  match 'ajoke/clients/update_client' => 'clients#update_client', via: [:post]
  match 'ajoke/clients/delete' => 'clients#delete', via: [:get]

  get 'images/upload_images'

  get 'ajoke/options'

  get 'ajoke/galleries'

  get 'ajoke/schedule'

  get 'ajoke/notifications'

  get 'ajoke/profile'

  match '/ajoke/create_gallery' => 'ajoke#create_gallery', via: [:post]
  match '/ajoke/upload_images' => 'ajoke#upload_images', via: [:get]
  match '/ajoke/add_photos' => 'ajoke#add_photos', via: [:get]
  match '/ajoke/uploaded_images' => 'ajoke#uploaded_images', via: [:get]
  match '/ajoke/update_cov' => 'ajoke#update_cov', via: [:post]
  match '/ajoke/save_images', :to => 'ajoke#save_images', :via => [:post, :put]
  match '/ajoke/upload_home' => 'ajoke#upload_home_images', via: [:get]
  match '/ajoke/delete_image' => 'ajoke#delete_image', via: [:post]

  devise_for :users

  devise_scope :user do
    match '/users/sign_out' => 'devise/sessions#destroy', via: [:get, :delete]
  end

  match '/about', :to => 'pages#about', :via => [:get]
  match '/gallery', :to => 'pages#gallery', :via => [:get]
  match '/galleries', :to => 'pages#galleries', :via => [:get]
  match '/view_gallery', :to => 'pages#view_gallery', :via => [:get]
  match '/packages', :to => 'pages#packages', :via => [:get]
  match '/contact', :to => 'pages#contact', :via => [:get, :post]
  match '/album_request', :to => 'pages#album_request', :via => [:get, :post]
  match '/ajoke', :to => 'ajoke#galleries', :via => [:get]
  match '/ajoke/save_cover', :to => 'ajoke#save_cover', :via => [:post, :put]

  root :to => 'pages#home'

end

app/views/pages/about.html.erb
<!-- Header _______________________________-->
<%= render "layouts/header", :locals => {:home_class => '',
										 :gal_class => '',
										 :pack_class =>'',
										 :about_class => 'current-menu-item',
										 :contact_class => '',
	                                     :body_class => 'post has-featured-image'} %>

<!-- MAIN CONTENT SECTION  _____________________________________________-->
	<section id="content" role="main">

		<div class="featured-image-header">
			<div id="">
				<%= image_tag("/images/4website/about.JPG", :alt => "") %>
			</div>
		</div>

		<div class="wrapper">
			<!-- WYSIWYG starts here __-->
			<div class="column-grid column-grid-3">
				<div class="column column-span-1 column-push-0 column-first">
					<h4><strong>Who are we</strong></h4>
				</div>
				<div class="column column-span-2 column-push-0 column-last">
					<p class=""><strong>Studio Nathan is a renowned establishment since 1983 with experienced professionals mastered in the art of prettifying people</strong></p>

					<p>We are located near the peaceful shores of Pondicherry and also operate from Chennai. Our vibrant set of professional wedding
					photographers never miss to capture the moment and our creative editors take pride in bringing life to the candid shots.
					We make sure that your sweet moments are cherished throughout your lifetime.  </p>
				</div>
			</div>

			<hr class="divider" />

			<div class="column-grid column-grid-3">
				<div class="column column-span-1 column-push-0 column-first">
					<h4><strong>What we do</strong></h4>
				</div>
				<div class="column column-span-2 column-push-0 column-last">
					<h5><strong>Weddings</strong></h5>
					<p>With all our focus on you, we only care about capturing your once in a lifetime moments. You are at your best, your emotions are peaking and you are surrounded by people who matter the most. Now, just imagine all the beautiful moments that will happen, Moments that we will help you to retain and treasure for life. We capture photo to help you relive those precious moments of love, laughter and happily ever after.</p>
					
					<h5><strong>Outdoor Photography</strong></h5>
					<p>We know the perfect places and have the best equipments to capture the real natural you.</p>


				</div>
			</div>



			<hr class="divider" />

			<div class="column-grid column-grid-3">
				<div class="column column-span-1 column-push-0 column-first">
					<h4><strong>Why Studio Nathan</strong></h4>
				</div>
				<div class="column column-span-2 column-push-0 column-last">
					<p>At Studio Nathan we make sure we carry the right gears to capture the moments as natural as they are and our photobooks acts as time machine to time travel your memories we use state of art technology with creativity to make that happen.</p>
				</div>
			</div>
			<hr class="divider" />

			<!-- WYSIWYG ends here __-->
		</div><!-- END .wrapper -->

	</section>
	<footer id="footer" role="contentinfo">
		<p class="copyright">studionathan &copy; 2016</p>
			<ul class="social-icons">
				<li><a href="#" target="_blank" title="Flickr"><i class="icon-flickr"></i></a></li>
				<li><a href="https://www.facebook.com/studionathan/" target="_blank" title="Facebook"><i class="icon-facebook"></i></a></li>
				<li><a href="#" target="_blank" title="Twitter"><i class="icon-twitter"></i></a></li>
			</ul>
	</footer>
<!-- Javascripts ______________________________________-->


<!-- include image popups -->
<%= javascript_include_tag "/javascripts/jquery.magnific-popup.min.js" %>

<!-- include svg line drawing plugin -->
<%= javascript_include_tag "/javascripts/jquery.lazylinepainter.min.js" %>

<!-- include custom script -->
<%= javascript_include_tag "/javascripts/scripts.js" %>

app/views/pages/ajoke.html.erb
<!-- Header _______________________________-->
<%= render "layouts/header", :locals => {} %>

<!-- MAIN CONTENT SECTION  _____________________________________________-->
	<section id="content" role="main">

		<div class="wrapper">

			<div id="blog-timeline">
				<!-- Settings menu ___-->
				<article class="active">
					<div class="entry-meta">
						<h2>Options  <i class="icon-cog"></i></h2>
					</div>
				</article>

				<article>
					<div class="entry-meta">
						<h2>Galleries  <i class="icon-pictures"></i></h2>
					</div>
				</article>

				<article>
					<div class="entry-meta">
						<h2>Clients  <i class="icon-diamond"></i></h2>
					</div>
				</article>

				<article>
					<div class="entry-meta">
						<h2>Schedule  <i class="icon-calendar"></i></h2>
					</div>
				</article>

				<article>
					<div class="entry-meta">
						<h2>Notifications  <i class="icon-lamp"></i></h2>
					</div>
				</article>

				<article>
					<div class="entry-meta">
						<h2>Profile  <i class="icon-clipboard"></i> </h2>
					</div>
				</article>


			</div><!-- END -->


			<!-- Shown selected page ___-->
			<div id="blog-post">
				<article class="entry post">

					<div class="entry-content">
						<!-- Heading ___-->
						<h3>Update Home page cover photo</h3>
						<p>Browse photo</p>
						<h3>Title</h3>
					</div>

				</article>
			</div><!-- END #blog-post -->


		</div><!-- END .wrapper -->

	</section>

<!-- Javascripts ______________________________________-->


<!-- include image popups -->
<%= javascript_include_tag "/javascripts/jquery.magnific-popup.min.js" %>

<!-- include svg line drawing plugin -->
<%= javascript_include_tag "/javascripts/jquery.lazylinepainter.min.js" %>

<!-- include custom script -->
<%= javascript_include_tag "/javascripts/scripts.js" %>

app/views/pages/album_request.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js" ></script>
<script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<!-- Header _______________________________-->
<%= render "layouts/header", :locals => {:home_class => '',
  :gal_class => '',
  :pack_class =>'',
  :about_class => '',
  :contact_class => '',
  :body_class => ''} %>
<!-- MAIN CONTENT SECTION  _____________________________________________-->
<section id="content" role="main">
  <div class="wrapper">
    <div class="column-grid column-grid-3">
      <div class="column column-span-1 column-push-0 column-first">
        <div id="pics" class="icons-showoff">
        </div>
      </div>
      <div id="form_container" class="column column-span-2 column-push-0 column-last">
        <h2>Submit request for Album making</h2>
        <p>Please fill in below form for making photo album with photos of your choise.</p>

        <div id="message"></div>
        <form method="post" action="#" name="albumform" id="albumform">

        <fieldset>
          <p class="form-column">
            <label for="name" accesskey="U"><span class="required">*</span> Your Name</label>
            <input name="name" type="text" id="name" size="30" value="" />
          </p>
          <p class="form-column">
            <label for="email" accesskey="E"><span class="required">*</span> Email</label>
            <input name="email" type="text" id="email" size="30" value="" />
          </p>
          <p class="form-column">
            <label for="phone" accesskey="P"><span class="required">*</span> Phone No</label>
            <input name="phone" type="text" id="phone" size="30" value="" />
          </p>
          <p class="form-column">
            <label for="photos" ><span class="required">*</span> Add selected photos for the album</label>
            <input name="photos" class="button blue" type="file" id="files" name="files[]" multiple />
            <input type="hidden" name="file_names" id="file_names" />
            <input type="submit" class="submit" id="submit" value="Submit" />
          </p>

          <p>
            <div class="notice info">
              <p>
                We only upload the names of files you selected. Don't worry about your data consumption.
              </p>
            </div>
          </p>
        </fieldset>

        </form>
      </div>
    </div>

  </div><!-- END .wrapper -->

</section>
<footer id="footer" role="contentinfo">
  <p class="copyright">studionathan &copy; 2016</p>
    <ul class="social-icons">
      <li><a href="#" target="_blank" title="Flickr"><i class="icon-flickr"></i></a></li>
      <li><a href="https://www.facebook.com/studionathan/" target="_blank" title="Facebook"><i class="icon-facebook"></i></a></li>
      <li><a href="#" target="_blank" title="Twitter"><i class="icon-twitter"></i></a></li>
    </ul>
</footer>
<!-- Javascripts ______________________________________-->
<!-- include image popups -->
<%= javascript_include_tag "/javascripts/jquery.magnific-popup.min.js" %>
<!-- include svg line drawing plugin -->
<%= javascript_include_tag "/javascripts/jquery.lazylinepainter.min.js" %>
<!-- include custom script -->
<%= javascript_include_tag "/javascripts/scripts.js" %>
<script>
function handleFileSelect(evt) {
  var files = [];

  if(evt.type =="change"){
    var files = evt.target.files; // FileList object
  }
  // files is a FileList of File objects. List some properties.
  var output = [];
  for (var i = 0, f; f = files[i]; i++) {
    //pth = window.URL.createObjectURL(f);
    //console.log("path=" + pth);
    //output.push('<p>', decodeURI(escape(f.name)), '</p>');
    output.push(decodeURI(escape(f.name)));
  }
  //document.getElementById('pics').innerHTML = output.join(''); //'<div class="notice info"><p style="width: 100%;">Preview of selected files</p></div>'
  $("#file_names").val(output.join(','));
  $("#pics").hide();
}
$(document).ready(function(){
  $("#files").val("");
  document.getElementById('files').addEventListener('change', handleFileSelect, false);
  $("#albumform").validate({

    // Specify the validation rules
    rules: {
      name: "required",
      photos: "required",
      phone: "required",
      email: {
          required: true,
          email: true
      }
    },

    // Specify the validation error messages
    messages: {
      name: "Please enter your name",
      photos: "Please select the photos for album",
      email: "Please enter a valid email address"
    },

    submitHandler: function(form) {
        form.ajaxSubmit();
        $("#form_container").html("<h2><center>Your photo album is in progress!</center></h2>")
    }
  });

});
(function(){
    // Check for the various File API support.
  if (window.File && window.FileReader && window.FileList && window.Blob) {
    //Browser requirement met!
  } else {
    alert('This feature is not supported in your browser. Please upgrade the browser or use a different one.');
  }
})();
</script>

app/views/pages/contact.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js" ></script>
<script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<%= javascript_include_tag "/javascripts/select2.min.js" %>
<!-- Header _______________________________-->
<%= render "layouts/header", :locals => {:home_class => '',
										 :gal_class => '',
										 :pack_class =>'',
										 :about_class => '',
										 :contact_class => 'current-menu-item',
	                                     :body_class => ''} %>

<!-- MAIN CONTENT SECTION  _____________________________________________-->
	<section id="content" role="main">


		<div class="wrapper">
			<!-- WYSIWYG starts here __-->

			<div class="column-grid column-grid-3">
				<div class="column column-span-1 column-push-0 column-first">
					<p class="big"><strong>T</strong>: &nbsp;  (+91) 9952474346<br />
					<strong>E</strong>:  &nbsp;  <a href="#">thestudionathan@gmail.com</a></p>


				</div>
				<div class="column column-span-2 column-push-0 column-last">
					<h2>Contact Us</h2>
					<p>Please fill in the following form to contact us</p>

					<div id="message"></div>
					<form method="post" action="#" name="contactform" id="contactform">

					<fieldset>
						<p class="form-column">
							<label for="name" accesskey="U"><span class="required">*</span> Your Name</label>
							<input name="name" type="text" id="name" size="30" value="" />
						</p>
						<p class="form-column">
							<label for="email" accesskey="E"><span class="required">*</span> Email</label>
							<input name="email" type="text" id="email" size="30" value="" />
						</p>
						<p class="form-column">
	            <label for="phone" accesskey="P"><span class="required">*</span> Phone No</label>
	            <input name="phone" type="text" id="phone" size="30" value="" />
	          </p>
						<p class="form-column">
							<label for="occation" > Occation</label>
							<select  multiple="multiple" name="occation" id="occation" size="30">
								<option value=""></option>
								<option value="outdoor">Outdoor shoot</option>
								<option value="reception">Reception</option>
								<option value="wedding">Wedding</option>
								<option value="birthday">Birthday</option>
							</select>
						</p>
						<p class="form-column">
							<label for="date" > Date</label>
							<input name="date" type="text" id="event_date" size="30" value="" />
						</p>
						<p>
							<label for="comments" accesskey="C"> Your comments</label>
							<textarea name="comments" cols="40" rows="3" id="comments"></textarea>
						</p>

						<p>
							<!-- <span class="required">*</span> Are you human?
							<%= recaptcha_tags %> -->

							<input type="submit" class="submit" id="submit" value="Submit" />
						</p>
					</fieldset>

					</form>
				</div>
			</div>

			<!-- WYSIWYG ends here __-->
		</div><!-- END .wrapper -->

	</section>

	<footer id="footer" role="contentinfo">
		<p class="copyright">studionathan &copy; 2016</p>
			<ul class="social-icons">
				<li><a href="#" target="_blank" title="Flickr"><i class="icon-flickr"></i></a></li>
				<li><a href="https://www.facebook.com/studionathan/" target="_blank" title="Facebook"><i class="icon-facebook"></i></a></li>
				<li><a href="#" target="_blank" title="Twitter"><i class="icon-twitter"></i></a></li>
			</ul>
	</footer>
<!-- Javascripts ______________________________________-->


<!-- include image popups -->
<%= javascript_include_tag "/javascripts/jquery.magnific-popup.min.js" %>

<!-- include svg line drawing plugin -->
<%= javascript_include_tag "/javascripts/jquery.lazylinepainter.min.js" %>

<!-- include custom script -->
<%= javascript_include_tag "/javascripts/scripts.js" %>
<script>
$(function() {
  $('#event_date').datepicker();
});
</script>

<script>
$(document).ready(function() {
	$("#occation").select2();

	// Setup form validation on the #register-form element
	$("#contactform").validate({

    // Specify the validation rules
    rules: {
      name: "required",
      // occation: "required",
			phone: "required",
      email: {
          required: true,
          email: true
      },
      // date: "required",
  	},

	  // Specify the validation error messages
	  messages: {
	    name: "Please enter your name",
	    occation: "Please enter your occation",
	    email: "Please enter a valid email address",
	    date: "Please enter date of your occation"
	  },

	  submitHandler: function(form) {
	      form.submit();
	  }
	});
});




</script>

app/views/pages/galleries.html.erb
<!-- Header _______________________________-->
<%= render "layouts/header", :locals => {:home_class => '',
										 :gal_class => 'current-menu-item',
										 :pack_class =>'',
										 :about_class => '',
										 :contact_class => '',
	                                     :body_class => ''} %>

<!-- MAIN CONTENT SECTION  _____________________________________________-->
<section id="content" role="main">
	<div class="wrapper">
		<h2>Photo Galleries</h2>
		<div style="text-align:center;padding:10px"> <%= will_paginate @galleries %> </div>
		<div  class="gallery masonry-gallery">
		<% @galleries.each do |gal| %>
			<% unless gal.cover.nil?
					pic = gal.images.find(gal.cover)
				else
					pic = gal.images.last
				end %>

			<figure id="gals" class="gallery-item" style="position: absolute; left: 0px; top: 0px;">
				<header class='gallery-icon'>
					<a class="galimg" href="<%=view_gallery_path %>?gallery=<%=gal.id %>" ><img data-id='<%= gal.id %>' src="<%= ( pic.nil? )? '' : pic.image.disp %>" alt="" /></a>
				</header>
				<figcaption class='gallery-caption'>
					<div  class="entry-summary">
						<h3><%= gal.name %></h3>
						<p id='img'><%= gal.event_date %></p>
					</div>
				</figcaption>
			</figure>
		<% end %>
		<% if @galleries.length == 0 %>
		<p style="text-align:center;">No galleries created yet. <p>
		<% end%>
		</div>
		<div style="text-align:center;padding:10px"> <%= will_paginate @galleries %> </div>


																					</div><!-- END .wrapper -->
																				</section>

<!-- Javascripts ______________________________________-->

<!-- include Masonry -->
<script src="/javascripts/isotope.pkgd.min.js"></script>
<!-- include image popups -->
<script src="/javascripts/jquery.magnific-popup.min.js"></script>
<!-- include mousewheel plugins -->
<script src="/javascripts/jquery.mousewheel.min.js"></script>
<!-- include carousel plugins -->
<script src="/javascripts/jquery.tinycarousel.min.js"></script>
<!-- include svg line drawing plugin -->
<script src="/javascripts/jquery.lazylinepainter.min.js"></script>
<!-- include custom script -->
<script src="/javascripts/scripts.js"></script>
<script>
$(function() {

	$(".galimg").click(function(e){
		e.preventDefault();
		var link = $(this).attr( 'href' );
		location.href=link;
});


});
</script>

app/views/pages/gallery.html.erb
<!-- Header _______________________________-->
<%= render "layouts/header", :locals => {:home_class => '',
										 :gal_class => 'current-menu-item',
										 :pack_class =>'',
										 :about_class => '',
										 :contact_class => '',
	                                     :body_class => ''} %>

<!-- MAIN CONTENT SECTION  _____________________________________________-->
	<section id="content" role="main">
    <div class="wrapper">
      <nav id="gallery-filter">
				<ul>
					<li><a href="/gallery" class= '<%= (params[:id].nil?)? "active" : ""%>' >All</a></li>
					<% @galleries.each do |gallery| %>
						<li><a href='/view_gallery/?id=<%= gallery.id %>' class= '<%= (params[:id].to_s == gallery.id.to_s)? "active" : ""%>'  ><%= gallery.name %></a></li>
					<% end %>
				</ul>
			</nav>
      <nav id="grid-changer">
				<ul>
					<li class="col-3"><a href="javascript:void(0)" class="active">
						<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30">
							<rect width="10" height="10" x="8"   y="8" />
						</svg>
					</a></li>
					<li class="col-5"><a href="javascript:void(0)">
						<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30">
							<rect width="7" height="7" x="6"   y="6" />
							<rect width="7" height="7" x="14" y="6" />
							<rect width="7" height="7" x="6" y="14" />
							<rect width="7" height="7" x="14" y="14" />
						</svg>
					</a></li>
				</ul>
			</nav>
      <!-- Gallery __-->
			<div  class="gallery masonry-gallery">
				<!-- <figure class="gallery-item outdoor">
					<header class='gallery-icon'>
						<a href="/images/forFBPage/01.jpg" class="popup" />
						<img class="lazy" src="/images/load.gif" data-orig="/images/forFBPage/01.jpg"alt="" /></a>
					</header>
				</figure> -->
				<% @photos.each do |photo| %>
				  <figure class="gallery-item <%= photo.gallery.name.downcase %>">
				    <header class='gallery-icon'>
				      <a href="<%= photo.image %>" class="popup" >
							<img class="lazy" src="/images/load.gif" data-orig="<%= photo.image.disp %>" alt="" /></a>
				    </header>
				  </figure>
				<% end %>
				<% if @photos.length == 0 %>
				<p style="text-align:center;">No photos added yet <p>
				<% end%>
			</div>
			<div style="text-align:center;padding:10px"> <%= will_paginate @photos %> </div>

		</div>
	</section>
	<footer id="footer" role="contentinfo">
		<p class="copyright">studionathan &copy; 2016</p>
			<ul class="social-icons">
				<li><a href="#" target="_blank" title="Flickr"><i class="icon-flickr"></i></a></li>
				<li><a href="https://www.facebook.com/studionathan/" target="_blank" title="Facebook"><i class="icon-facebook"></i></a></li>
				<li><a href="#" target="_blank" title="Twitter"><i class="icon-twitter"></i></a></li>
			</ul>
	</footer>
<!-- Javascripts ______________________________________-->

<%= javascript_include_tag "/javascripts/isotope.pkgd.min.js" %>
<!-- include image popups -->
<%= javascript_include_tag "/javascripts/jquery.magnific-popup.min.js" %>

<!-- include svg line drawing plugin -->
<%= javascript_include_tag "/javascripts/jquery.lazylinepainter.min.js" %>

<!-- include custom script -->
<%= javascript_include_tag "/javascripts/scripts.js" %>
<script>
jQuery(document).ready(function ($) {
	$("#gallery-filter li a").click(function(e){
		window.location.href = $(this).attr("href");
	})
    $("img.lazy").lazyload(
        { data_attribute: "orig"
        });
		$('html, body').animate({ scrollTop: $('#gallery-filter').offset().top}, 1000);
});

</script>

app/views/pages/home.html.erb
<!-- Header _______________________________-->
<%= render "layouts/header", :locals => {:home_class => 'current-menu-item',
										 :gal_class => '',
										 :pack_class =>'',
										 :about_class => '',
										 :contact_class => '',
	                                     :body_class => 'home fullscreen'} %>


<!-- MAIN CONTENT SECTION  _____________________________________________-->
	<section id="content" role="main">
		<div class="wrapper">
			<!-- WYSIWYG -->
			<div class="gallery fullscreen-gallery">
				<% @photos.each do |photo| %>
				  <figure class="gallery-item <%= photo.gallery.name.downcase %>">
				    <header class='gallery-icon'>
				      <a href="#">
								<img class="lazy" src="<%= photo.image.thumb %>" data-orig="<%= photo.image %>" alt="" />
							</a>
				    </header>
						<figcaption class='gallery-caption'>
							<div class="entry-summary">
								<h2>Professional Candid Wedding Photography Services</h2>
							</div>
						</figcaption>
				  </figure>
				<% end %>
				<% if @photos.length == 0 %>
					<figure class="gallery-item">
						<header class='gallery-icon'>
							<a href="#"><img class="lazy" src="/images/load.gif" data-orig="images/4website/1.jpg"  alt="" /></a>
						</header>
						<figcaption class='gallery-caption'>
							<div class="entry-summary">
								<h2>Professional Candid Wedding Photography Services</h2>
							</div>
						</figcaption>
					</figure>
				<% end%>
		</div>


			<!-- END WYSIWYG -->

		</div><!-- END .wrapper -->
	</section>
	<footer id="footer" role="contentinfo">
		<p class="copyright">studionathan &copy; 2016</p>
			<ul class="social-icons">
				<li><a href="#" target="_blank" title="Flickr"><i class="icon-flickr"></i></a></li>
				<li><a href="https://www.facebook.com/studionathan/" target="_blank" title="Facebook"><i class="icon-facebook"></i></a></li>
				<li><a href="#" target="_blank" title="Twitter"><i class="icon-twitter"></i></a></li>
			</ul>
	</footer>

<!-- Javascripts ______________________________________-->
<%= javascript_include_tag "/javascripts/retina.min.js" %>
<!-- include Masonry -->
<%= javascript_include_tag "/javascripts/isotope.pkgd.min.js" %>
<!-- include image popups -->
<%= javascript_include_tag "/javascripts/jquery.magnific-popup.min.js" %>
<!-- include mousewheel plugins -->
<%= javascript_include_tag "/javascripts/jquery.mousewheel.min.js" %>
<!-- include gallery cycle plugin -->
<%= javascript_include_tag "/javascripts/jquery.cycle.min.js" %>
<!-- include carousel plugins -->
<%= javascript_include_tag "/javascripts/jquery.tinycarousel.min.js" %>
<!-- include svg line drawing plugin -->
<%= javascript_include_tag "/javascripts/jquery.lazylinepainter.min.js" %>

<script>
$("#logo").hide()
</script>
<!-- include custom script -->
<%= javascript_include_tag "scripts.js" %>
<script>
jQuery(document).ready(function() {
	$("img.lazy").lazyload(
			{ data_attribute: "orig",
				threshold : 200
			});
});
</script>