config/routes.rb
Rails.application.routes.draw do

  match 'ajoke/clients' => 'clients#index', via: [:get]

  match 'ajoke/clients/create' => 'clients#create', via: [:post]

  match 'ajoke/clients/edit' => 'clients#edit', via: [:get]
  patch 'ajoke/clients/update' => 'clients#update'
  match 'ajoke/clients/update_client' => 'clients#update_client', via: [:post]
  match 'ajoke/clients/delete' => 'clients#delete', via: [:get]

  get 'images/upload_images'

  get 'ajoke/options'

  get 'ajoke/galleries'

  get 'ajoke/schedule'

  get 'ajoke/notifications'

  get 'ajoke/profile'

  match '/ajoke/create_gallery' => 'ajoke#create_gallery', via: [:post]
  match '/ajoke/upload_images' => 'ajoke#upload_images', via: [:get]
  match '/ajoke/add_photos' => 'ajoke#add_photos', via: [:get]
  match '/ajoke/uploaded_images' => 'ajoke#uploaded_images', via: [:get]
  match '/ajoke/update_cov' => 'ajoke#update_cov', via: [:post]
  match '/ajoke/save_images', :to => 'ajoke#save_images', :via => [:post, :put]
  match '/ajoke/upload_home' => 'ajoke#upload_home_images', via: [:get]
  match '/ajoke/delete_image' => 'ajoke#delete_image', via: [:post]

  devise_for :users

  devise_scope :user do
    match '/users/sign_out' => 'devise/sessions#destroy', via: [:get, :delete]
  end

  match '/about', :to => 'pages#about', :via => [:get]
  match '/gallery', :to => 'pages#gallery', :via => [:get]
  match '/galleries', :to => 'pages#galleries', :via => [:get]
  match '/view_gallery', :to => 'pages#view_gallery', :via => [:get]
  match '/packages', :to => 'pages#packages', :via => [:get]
  match '/contact', :to => 'pages#contact', :via => [:get, :post]
  match '/album_request', :to => 'pages#album_request', :via => [:get, :post]
  match '/ajoke', :to => 'ajoke#galleries', :via => [:get]
  match '/ajoke/save_cover', :to => 'ajoke#save_cover', :via => [:post, :put]

  root :to => 'pages#home'

end

app/views/layouts/_error_messages.html.erb
<% unless object.errors.empty? %>
	<script type="text/javascript">
    console.log("Here???")
		<% object.errors.full_messages.each do |msg| %>
			toastr['error']('<%= msg %>');
		<% end %>
	</script>
<% end %>

app/views/layouts/_footer.html.erb
<script src="/javascripts/retina.min.js"></script>

<!-- include accordion / tabs plugin -->
<script src="/javascripts/whistles.min.js"></script>
<!-- include mousewheel plugins -->
<script src="/javascripts/jquery.mousewheel.min.js"></script>
<% unless notice.nil? or notice.empty? %>
	<script type="text/javascript">
		toastr['success']('<%= notice %>');
	</script>
<% end %>
<% unless alert.nil? or alert.empty? %>
	<script type="text/javascript">
	console.log('<%=alert%>');
		toastr['error']('<%= alert %>');
	</script>
<% end %>
<!-- Google Analytics-->
<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-71913468-1', 'auto');
	ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<body class="<%= locals[:body_class] %>">
  <!-- Loader _______________________________-->
 <!-- <div class="loadreveal"></div>
 <div id="loadscreen"><div id="loader"><span></span></div></div> -->

    <header role="banner" id="header">

		<div class="wrapper">

			<!-- Logo __-->
			<h1 id="logo">
				<%= link_to logo, root_path %>
			</h1>

			<!-- Main menu __-->
			<nav id="mainmenu" role="navigation">

				<div id="menu-burger"><i class="icon-menu"></i></div>

				<div id="menu">
					<ul>
            <% uri = URI.parse(request.original_url) %>
						<li class="<%= locals[:home_class] %>"><%= link_to("Home", root_path) %></li>
            <li class="<%= locals[:gal_class] %>"><%= link_to("Gallery", gallery_path) %></li>
				    <!--
            <li class="<%= locals[:gal_class] %>"><%= link_to("Galleries", galleries_path) %></li>
						<li class="<%= locals[:pack_class] %>"><%= link_to("Packages", packages_path)%></li>
            !-->
						<li class="<%= locals[:about_class] %>"><%= link_to("About", about_path) %></li>
						<li class="<%= locals[:contact_class] %>"><%= link_to("Contact", contact_path) %></li>
						<% if user_signed_in? %>
              <li class="<%= (uri.path.include? ajoke_path)? 'current-menu-item' : '' %>"><%= link_to("Admin", ajoke_path) %></li>
							<li><%= link_to("Logout", destroy_user_session_path, method: :delete) %></li>
						<% end%>
					</ul>
				</div>
			</nav>
		</div> <!-- END .wrapper -->

	</header>

app/views/layouts/_stylesheets.html.erb
<link href='//fonts.googleapis.com/css?family=Josefin+Sans:400,600&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>

<!-- Fixing Internet Explorer ______________________________________-->
<!--[if lt IE 9]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag "application" %>
<%= stylesheet_link_tag 'icomoon', :media => 'screen' %>
<%= stylesheet_link_tag 'magnificpopup', :media => 'screen' %>
<%= stylesheet_link_tag 'columns.min', :media => 'screen' %>
<%= stylesheet_link_tag 'style', :media => 'screen' %>
<link href="/stylesheets/select2.css" rel="stylesheet">
<link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet"/>
<%= javascript_include_tag "application" %>
<%= javascript_include_tag "/javascripts/retina.min.js" %>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<!--[if lt IE 9]>
   <%= stylesheet_link_tag 'ie' %>
<![endif]-->

app/views/layouts/ajoke.html.erb
<!DOCTYPE html >
<html>
   <head>
      <meta charset="utf-8">

     <link rel="Shortcut Icon" type="image/ico" href="favicon.ico" />
     <meta name="viewport" content="width=device-width, initial-scale=1" />

     <title><%= title %></title>
     <%= csrf_meta_tag %>
     <%= render "layouts/stylesheets" %>
     <!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
      <link rel="stylesheet" href="/stylesheets/jquery.fileupload.css">
      <link rel="stylesheet" href="/stylesheets/jquery.fileupload-ui.css">
      <link rel="stylesheet" href="/stylesheets/chosen/chosen.css">
      <style>
        div.entry-summary a:hover {
          color:#F7F6F5;
        }
      </style>
      <script src="/javascripts/isotope.pkgd.min.js"></script>
   </head>
  <!-- Header _______________________________-->
  <%= render "layouts/header", :locals => {} %>

  <!-- MAIN CONTENT SECTION  _____________________________________________-->
	<section id="content" role="main">

		<div class="wrapper">

			<div id="blog-timeline">
        <% uri = URI.parse(request.original_url) %>
        <!-- Settings menu ___-->
				<!-- <article class="<%= (uri.path == ajoke_path)? "active" : (uri.path == ajoke_options_path)? "active" : "" %>">
					<div class="entry-meta">
						<a href="/ajoke/options" style="<%= (uri.path == ajoke_path)? "" : (uri.path == ajoke_options_path)? "" : "color:inherit;" %>"><h2>Options  <i class="icon-cog"></i></h2></a>
					</div>
				</article> -->

				<article class="<%= (uri.path == ajoke_path)? "active" : (uri.path === ajoke_galleries_path)? "active" : (uri.path == ajoke_upload_images_path)? "active" : (uri.path == ajoke_add_photos_path)? "active" : "" %>">
					<div class="entry-meta">
						<a href="/ajoke/galleries" style="<%= (uri.path === ajoke_galleries_path)? "" : (uri.path == ajoke_upload_images_path)? "" : (uri.path == ajoke_add_photos_path)? "" : "color:inherit;" %>"><h2>Galleries  <i class="icon-pictures"></i></h2></a>
					</div>
				</article>

				<article class="<%= (uri.path === ajoke_clients_path)? "active" : (uri.path === ajoke_clients_edit_path)? "active" : "" %>">
					<div class="entry-meta">
						<a href="/ajoke/clients" style="<%= (uri.path === ajoke_clients_path)? "" : (uri.path === ajoke_clients_edit_path)? "" : "color:inherit;" %>"><h2>Clients  <i class="icon-diamond"></i></h2></a>
					</div>
				</article>

				<article class="<%= (uri.path === ajoke_schedule_path)? "active" : "" %>">
					<div class="entry-meta">
						<a href="/ajoke/schedule" style="<%= (uri.path === ajoke_schedule_path)? "" : "color:inherit;" %>"><h2>Schedule  <i class="icon-calendar"></i></h2></a>
					</div>
				</article>

				<article class="<%= (uri.path === ajoke_notifications_path)? "active" : "" %>">
					<div class="entry-meta">
						<a href="/ajoke/notifications" style="<%= (uri.path === ajoke_notifications_path)? "" : "color:inherit;" %>"><h2>Notifications  <i class="icon-lamp"></i></h2></a>
					</div>
				</article>

				<article class="<%= (uri.path === ajoke_profile_path)? "active" : "" %>">
					<div class="entry-meta">
						<a href="/ajoke/profile" style="<%= (uri.path === ajoke_profile_path)? "" : "color:inherit;" %>"><h2>Profile  <i class="icon-clipboard"></i> </h2></a>
					</div>
				</article>


			</div><!-- END -->


			<!-- Shown selected page ___-->
			<div id="blog-post">
				<article class="entry post">

					<div class="entry-content">
            <%= yield %>
					</div>

				</article>
			</div><!-- END #blog-post -->


		</div><!-- END .wrapper -->

	</section>

<!-- Javascripts ______________________________________-->


<!-- include image popups -->
<%= javascript_include_tag "/javascripts/jquery.magnific-popup.min.js" %>

<!-- include svg line drawing plugin -->
<%= javascript_include_tag "/javascripts/jquery.lazylinepainter.min.js" %>

<!-- include custom script -->
<%= javascript_include_tag "/javascripts/scripts.js" %>

<%= render "layouts/footer"  %>
<%= debug(params) if Rails.env.development? %>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html >
<html>
 <head>
    <meta charset="utf-8">

   <link rel="Shortcut Icon" type="image/ico" href="favicon.ico" />
   <meta name="viewport" content="width=device-width, initial-scale=1" />

   <title><%= title %></title>
   <%= csrf_meta_tag %>
   <%= render "layouts/stylesheets" %>
   <link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.css" rel="stylesheet">

   <script  language="javascript">
      document.onmousedown = disableclick;
      document.oncontextmenu = new Function("return false");
      status="Right Click Disabled";
      function disableclick(event)
      {
        if(event.button==2)
         {
           console.log(status);
           return false;
         }
      };
    </script>

    <%= javascript_include_tag "/javascripts/jquery.lazyload.min.js" %>

 </head>

	<%= yield %>

	<%= render "layouts/footer"  %>


 </body>

</html>

app/views/layouts/image.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
   <title><%= title %></title>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
   <meta name="viewport" content="width=device-width, initial-scale=1.0, minimal-ui"/>
   <%= csrf_meta_tag %>
   <link href='//fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'/>
   <link rel="shortcut icon" href="img/favicon.ico"/>
   <!--[if lte IE 8]>
    <link rel="stylesheet" type="text/css" href="/gallery/css/css_ie.css" />
  <![endif]-->

  <link rel="stylesheet" type="text/css" href="/gallery/css/css.css" media="screen" />
  <link media="screen" href="/gallery/css/responsive.css" type="text/css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="/gallery/css/pagination.css" media="screen" />
  <link rel="stylesheet" type='text/css' href='/gallery/js/simplemodal/css/basic.css' media='screen' />
  <link rel="stylesheet" type="text/css" href="/gallery/js/superfish/css/superfish.css" media="screen" />
  <link rel="stylesheet" type="text/css" href="/gallery/js/superfish/css/superfish-vertical.css" media="screen" />
  <link rel="stylesheet" type="text/css" href="/gallery/js/fancybox/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
  <link rel="stylesheet" type="text/css" href="/gallery/js/jScrollPane/style/jquery.jscrollpane.css" media="all" />
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
  <script type="text/javascript" src="/gallery/js/carouFredSel/jquery.carouFredSel-3.2.1-packed.js"></script>
  <script type='text/javascript' src='/gallery/js/debouncedresize/jquery.debouncedresize.js'></script>
  <script type="text/javascript" src="/gallery/js/timer/jquery.timers.js"></script>
  <script type="text/javascript" src='/gallery/js/simplemodal/js/jquery.simplemodal.js'></script>
  <script type="text/javascript" src="/gallery/js/superfish/js/hoverIntent.js"></script>
  <script type="text/javascript" src="/gallery/js/superfish/js/superfish.js"></script>
  <script type="text/javascript" src="/gallery/js/fancybox/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
  <script src="/gallery/js/TinyNav/tinynav.min.js" type="text/javascript"></script>
  <script src="/gallery/js/touchSwipe/jquery.touchSwipe.min.js" type="text/javascript"></script>
  <script src="/gallery/js/lazyload/jquery.lazyload.min.js" type="text/javascript"></script>
  <script src="/gallery/js/responsiveslides/responsiveslides.min.js" type="text/javascript"></script>
  <script type="text/javascript" src="/gallery/js/fancybox/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
  <script type="text/javascript" src="/gallery/js/qtip/jquery.qtip-1.0.0-rc3.min.js"></script>
  <script type="text/javascript" src="/gallery/js/filterable/js/filterable.js" ></script>
  <script type="text/javascript" src="/gallery/js/config.js"></script>
  <script type="text/javascript" src="/gallery/js/big_gallery.js"></script>
  <script type="text/javascript" src="/gallery/js/validate.js"></script>
  <script type="text/javascript" src="/gallery/js/jScrollPane/script/jquery.jscrollpane.min.js"></script>
  <script type="text/javascript" src="/gallery/js/jScrollPane/script/jquery.mousewheel.js"></script>
 </head>
 <script type="text/javascript">var slideSize='height';</script>
 <body id="body">
   <!-- Page loading icon -->
   <div id="loader"><img src="/gallery/img/loader2.gif" alt="please wait, site is loading"/></div>
   <!-- Logo -->
   <div id="logo"><a href="<%= root_path %>" title="Hariprasanth Prasa Photography"></a></div>
   <!-- Menu show -->
   <div id="menu-show"><div id="menu-show-arrow"></div></div>
   <div id="menu-hide"><div id="menu-hide-arrow"></div></div>
   <!-- Menu div start -->
   <div id="menu">
   		<!-- Superfish menu start -->
   		<ul class="sf-menu sf-vertical">
         <li ><%= link_to("HOME", root_path) %></li>
         <li ><%= link_to("GALLERIES", galleries_path) %></li>
         <li ><%= link_to("PACKAGES", packages_path)%></li>
         <li ><%= link_to("ABOUT", about_path) %></li>
         <li ><%= link_to("CONTACT", contact_path) %></li>

   		</ul><!-- Superfish menu end -->

   		<ul class="follow">
   			<li>FOLLOW ME:</li>
   			<li>
   				<ul>
   					<li><a href="#" title="Facebook" class="qtip"><img src="/gallery/img/icons/social/facebook.png" alt="Facebook" /></a></li>
   					<li><a href="#" title="Twitter" class="qtip"><img src="/gallery/img/icons/social/twitter.png" alt="Twitter" /></a></li>
   					<li><a href="#" title="Google Plus" class="qtip"><img src="/gallery/img/icons/social/gplus.png" alt="Google Plus" /></a></li>
   					<li><a href="#" title="Flickr" class="qtip"><img src="/gallery/img/icons/social/flickr.png" alt="Flickr" /></a></li>
   				</ul>
   			</li>
   		</ul><!-- Social and stock icons end -->
   </div><!-- Menu div end -->
	 <%= yield %>
 </body>

</html>